import { NextResponse } from "next/server"
import type { CarPersona } from "@/types"

export async function GET() {
  try {
    // In a real app, this would fetch from a database
    // For now, we'll return mock data
    const cars: CarPersona[] = [
      {
        id: "car_1",
        model: "GLC 300 Coupe",
        year: 2021,
        modelIdentity: "Executive",
        usageHistory: "City-driven",
        ownershipStyle: "Single-owner",
        serviceBehavior: "Regularly maintained",
        emotionalTone: "Loyal Companion",
        visualVibe: "Sleek",
        interiorEnergy: "Tech-heavy",
        notableMemories: ["Long coastal drives", "City nights"],
        drivingFeel: "Smooth",
        voice: "Confident",
        matchScore: 93,
        matchExplanation: "Perfect for city driving, Matches your aesthetic, Aligns with your values",
        image: "/images/glc-coupe-front.avif",
        color: "Obsidian Black",
      },
      {
        id: "car_2",
        model: "E-Class",
        year: 2022,
        modelIdentity: "Classic",
        usageHistory: "Long-distance",
        ownershipStyle: "Single-owner",
        serviceBehavior: "Fully documented",
        emotionalTone: "Nostalgic",
        visualVibe: "Understated",
        interiorEnergy: "Minimalist",
        notableMemories: ["Business trips", "Family vacations"],
        drivingFeel: "Relaxed",
        voice: "Wise",
        matchScore: 81,
        matchExplanation: "Great for comfort, Ideal for long drives, Matches your weekend style",
        image: "/images/e-class.png",
        color: "Selenite Grey",
      },
      {
        id: "car_3",
        model: "CLS",
        year: 2020,
        modelIdentity: "Sporty",
        usageHistory: "Light use",
        ownershipStyle: "Collector-owned",
        serviceBehavior: "Regularly maintained",
        emotionalTone: "Wild Spirit",
        visualVibe: "Bold",
        interiorEnergy: "Driver-focused",
        notableMemories: ["Track days", "Mountain passes"],
        drivingFeel: "Aggressive",
        voice: "Playful",
        matchScore: 85,
        matchExplanation: "Perfect for spirited driving, Matches your bold style, Great for adventures",
        image: "/images/cls.jpg",
        color: "Designo Diamond White",
      },
      {
        id: "car_4",
        model: "S-Class",
        year: 2023,
        modelIdentity: "Luxury",
        usageHistory: "Executive transport",
        ownershipStyle: "Corporate fleet",
        serviceBehavior: "Premium maintenance",
        emotionalTone: "Distinguished",
        visualVibe: "Elegant",
        interiorEnergy: "Opulent",
        notableMemories: ["VIP transportation", "Business summits"],
        drivingFeel: "Effortless",
        voice: "Sophisticated",
        matchScore: 78,
        matchExplanation: "Luxury focused, Premium comfort, Executive style",
        image: "/images/s-class.png",
        color: "Anthracite Blue",
      },
      {
        id: "car_5",
        model: "AMG GT",
        year: 2022,
        modelIdentity: "Performance",
        usageHistory: "Weekend drives",
        ownershipStyle: "Enthusiast-owned",
        serviceBehavior: "Performance-tuned",
        emotionalTone: "Exhilarating",
        visualVibe: "Aggressive",
        interiorEnergy: "Race-inspired",
        notableMemories: ["Track days", "Mountain passes", "Autobahn runs"],
        drivingFeel: "Precise",
        voice: "Intense",
        matchScore: 72,
        matchExplanation: "Performance focused, Driving enthusiast appeal, Weekend thrill",
        image: "/images/amg-gt.png",
        color: "Solar Beam Yellow",
      },
      {
        id: "car_6",
        model: "EQS",
        year: 2023,
        modelIdentity: "Futuristic",
        usageHistory: "Daily commute",
        ownershipStyle: "Tech enthusiast",
        serviceBehavior: "Software updates",
        emotionalTone: "Forward-thinking",
        visualVibe: "Cutting-edge",
        interiorEnergy: "Digital sanctuary",
        notableMemories: ["Zero-emission journeys", "Tech showcases"],
        drivingFeel: "Silent",
        voice: "Innovative",
        matchScore: 89,
        matchExplanation: "Tech-forward, Environmentally conscious, Modern aesthetic",
        image: "/images/eqs.png",
        color: "High-Tech Silver",
      },
    ]

    return NextResponse.json(cars)
  } catch (error) {
    console.error("Error fetching cars:", error)
    return NextResponse.json({ error: "Failed to fetch cars" }, { status: 500 })
  }
}
